### ISSUE TITLE
Crash and radiocommands 

### ISSUE THREAD

**Issue by szogi1910** [splewis/csgo-multi-1v1#175] opened 2017-08-13 16:45 UTC
### Steps to reproduce  @splewis 
- Plugin version: 1.1.5"
- Sourcemod version:  1.8.0.6017
- Metamod version:= "1.10.7-devV" ( def. "1.10.7-dev" ) notify singleplayer      - Metamod:Source Version

Crash logs:
https://crash.limetech.org/mi7e3yi5uk2j

**Comment by splewis** [comment] 2017-08-23 01:02
I'm not sure why you closed this: I'm assuming you have the problem still since you posted https://forums.alliedmods.net/showpost.php?p=2543673&postcount=1329 with https://crash.limetech.org/3j5jaxdhmyca

I have no way to reproduce this yet. I would try disabling any other plugins you have that are drawing menus.

**Comment by szogi1910** [comment] 2017-08-23 10:33
By accident I close this application
I already write how can reproduce the error

When crashu comes through using two commands
Use the first command !Rs - https://forums.alliedmods.net/showthread.php?p=1871412
Use the command sm_admin - https://forums.alliedmods.net/showthread.php?t=263735

With older versions, the fashion in the current configuration all worked fine

**Closed** 2017-09-10 18:01 UTC
