### ISSUE TITLE
Crash 12/6/2018

### ISSUE THREAD

**Issue by ThanhByKyTa** [splewis/csgo-multi-1v1#211] opened 2018-12-08 04:39 UTC
When 2 player join server auto crash server
SM 1.9 6266
![image](https://user-images.githubusercontent.com/33537916/49681984-bb2ff980-fadd-11e8-8a9c-5b4b975da40c.png)

**Comment by splewis** [comment] 2018-12-08 04:42
You've given no evidence this is a multi1v1 issue.

You're probably using some other plugin or extension causing the crash.

**Comment by ThanhByKyTa** [comment] 2018-12-08 08:55
![image](https://user-images.githubusercontent.com/33537916/49684112-b67d3c80-fb01-11e8-86db-62f943e75fd4.png)

**Comment by ThanhByKyTa** [comment] 2018-12-08 08:56
![image](https://user-images.githubusercontent.com/33537916/49684123-df053680-fb01-11e8-907a-243132a1daa8.png)

**Comment by ThanhByKyTa** [comment] 2018-12-08 08:57
01 "Admin File Reader" (1.9.0.6257) by AlliedModders LLC
  02 "Admin Help" (1.9.0.6257) by AlliedModders LLC
  03 "Admin Menu" (1.9.0.6257) by AlliedModders LLC
  04 "Anti-Flood" (1.9.0.6257) by AlliedModders LLC
  05 "Basic Chat" (1.9.0.6257) by AlliedModders LLC
  06 "Basic Comm Control" (1.9.0.6257) by AlliedModders LLC
  07 "Basic Commands" (1.9.0.6257) by AlliedModders LLC
  08 "Basic Info Triggers" (1.9.0.6257) by AlliedModders LLC
  09 "Basic Votes" (1.9.0.6257) by AlliedModders LLC
  10 "Dynamic" (0.0.29) by Neuro Toxin
  11 "NativeVotes Basic Commands" (1.0) by Powerlord and AlliedModders LLC
  12 "NativeVotes" (0.8.3) by Powerlord
  13  "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
  14 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
  15 "bykyta\sbp.smx"
  16 "Self-Mute" (1.03) by Otokiru ,edit 93x, Accelerator
  17 "Server Hop" (0.8.2) by [GRAVE] rig0r
  18 "bykyta\sv_disable_motd_0.smx"
  19 "Updater" (1.2.2) by GoD-Tony
  20 "Chat-Processor" (2.1.4) by Keith Warren (Shaders Allen)
  21 "Client Preferences" (1.9.0.6257) by AlliedModders LLC
  22 "Fun Commands" (1.9.0.6257) by AlliedModders LLC
  23 "Fun Votes" (1.9.0.6257) by AlliedModders LLC
  24 "HUD" (2.0) by edw
  25 "MapChooser" (1.9.0.6257) by AlliedModders LLC
  26 "Join Team" (1.0) by Divin!
  27 "CS:GO Multi1v1" (1.1.9) by splewis
  28 "[CSGO]Multi 1v1 - Deagle 1 Tap" (1.0) by S4muRaY'
  29 "CS:GO Multi1v1: Dodgeball round addon" (1.0.1) by Franc1sco franug
  30 "CS:GO Multi1v1: flashbangs addon" (1.1.9) by splewis
  31 "CS:GO Multi1v1: headshot round addon" (1.0.0) by Bara
  32 "CS:GO Multi1v1: He grenade battle round addon" (1.1) by Franc1sco franug
  33 "CS:GO Multi1v1: knife round addon" (1.1.9) by splewis
  34 "[CSGO]Multi 1v1 - No Scope" (1.0) by S4muRaY'
  35 "CS:GO Multi1v1: online stats viewer" (1.1.9) by splewis
  36 "CS:GO Multi1v1: Only HS option" (1.2) by Franc1sco franug
  37 "Arena Country TAG" (1.0) by ESK0
  38  "Nextmap" (1.9.0.6257) by AlliedModders LLC
  39 "[CSS/CS:GO] AbNeR ResetScore" (1.5fix) by AbNeR_CSS
  40 "SM Access By Steam Group" (1.3) by Franc1sco franug
  41 "alltalk" (1.0) by Hattrick (HKS)
  42 "Death Broadcast" (1.00) by R3TROATTACK
  43 "Arena Kill Distance" (1.00) by hadesownage
  44 "Gloves" (1.0.3) by ByKyTa | ByKyTaGaming.Com
  45 "hextags" (1.201) by Hexah
  46 "[Multi-1v1] Challenge" (1.1.4) by Headline
  47 "CSGO Panorama Map Change Crashe Fixer" (1.0.6) by BOT Benson
  48 "No Bots" (1.0) by .#Zipcore
  49 "[CSGO] ChickenSlayer" (0.1.1) by Entity
  50 "[AWP] No-Scope Detector" (1.2.6_debug2) by Ak0 (improved by Grey83 & onehand)
  51 "Player Commands" (1.9.0.6257) by AlliedModders LLC
  52 "RandomCycle" (1.9.0.6252) by AlliedModders LLC
  53 "Reserved Slots" (1.9.0.6257) by AlliedModders LLC
  54 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBans++ Dev Team
  55 "SourceBans++: Bans Checker" (1.6.3) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  56 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
  57 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceBans++ Dev Team
  58 "SourceBans++ Report Plugin" (1.6.3) by RumbleFrog, SourceBans++ Dev Team
  59 "Sound Commands" (1.9.0.6257) by AlliedModders LLC
  60 "VPP Advertisement Plugin" (1.4.5.7) by VPP Gaming Network & SM9();
  61 "Weapons & Knives" (1.3.1) by kgns | oyunhost.net

**Comment by morpig** [comment] 2018-12-08 10:38
@ThanhByKyTa refer to #210

**Comment by patsToms** [comment] 2018-12-08 15:43
Having the same issue. Before f2p update it was working well.

Server is still crashing with mp_disconnect_kills_players set to 0.

**Comment by morpig** [comment] 2018-12-08 15:46
@patsToms do you have the weapons plugin made by kgns? that's another culprit from my side

**Comment by ThanhByKyTa** [comment] 2018-12-08 16:43
![image](https://user-images.githubusercontent.com/33537916/49688343-f9133900-fb42-11e8-919a-f871bca05b6b.png)

What thas ?

**Comment by splewis** [comment] 2018-12-08 17:44
> 61 "Weapons & Knives" (1.3.1) by kgns | oyunhost.net

Don't use shady plugins if you want your server to work.

**Comment by Javierko** [comment] 2018-12-08 18:15
If i can help you, my server is crashing too.
Here is https://crash.limetech.org/m7eojmokyffm

**Comment by splewis** [comment] 2018-12-09 01:42
I'm going to close this for now since I haven't seen any evidence there is a change needed in the plugin.

If someone has reproducible crashed with multi1v1 + stock sm plugins/extensions, that'd be interesting, but I haven't seen that so far.

**Closed by splewis** 2018-12-09 01:42 UTC
