### ISSUE TITLE
SQL errors

### ISSUE THREAD

**Issue by keigel2001** [splewis/csgo-multi-1v1#188] opened 2017-11-04 22:18 UTC
For the past weeks I sometimes get errors like these:

```L 11/02/2017 - 15:07:09: SourceMod error session started
L 11/02/2017 - 15:07:09: Info (map "am_must2") (file "errors_20171102.log")
L 11/02/2017 - 15:07:09: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xF0\x9F\x8E\x84  ...' for column 'name' at row 1
L 11/02/2017 - 15:13:22: Error log file session closed.
L 11/02/2017 - 16:29:55: SourceMod error session started
L 11/02/2017 - 16:29:55: Info (map "am_travesty") (file "errors_20171102.log")
L 11/02/2017 - 16:29:55: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xF0\x9D\x99\x9A\xF0\x9D...' for column 'name' at row 1
L 11/02/2017 - 16:39:03: Error log file session closed.
L 11/02/2017 - 16:44:55: SourceMod error session started
L 11/02/2017 - 16:44:55: Info (map "am_dust2") (file "errors_20171102.log")
L 11/02/2017 - 16:44:55: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xF0\x9D\x99\x9A\xF0\x9D...' for column 'name' at row 1
L 11/02/2017 - 16:54:52: Error log file session closed.
L 11/02/2017 - 21:05:03: SourceMod error session started
L 11/02/2017 - 21:05:03: Info (map "am_must2") (file "errors_20171102.log")
L 11/02/2017 - 21:05:03: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xF0\x9F\x8C\xB8' for column 'name' at row 1
L 11/02/2017 - 21:15:24: Error log file session closed.
L 11/02/2017 - 21:15:31: SourceMod error session started
L 11/02/2017 - 21:15:31: Info (map "am_arena") (file "errors_20171102.log")
L 11/02/2017 - 21:15:31: [multi1v1.smx] Last SQL Error: Incorrect string value: '\xF0\x9F\x8C\xB8' for column 'name' at row 1
L 11/02/2017 - 21:31:21: Error log file session closed.
```

I changed nothing (csgo related). So I think it's either bad escaping of a new player with a strange playername or related to the MYSQL strict mode of [MariaDB 10.2](https://mariadb.com/kb/en/library/upgrading-from-mariadb-101-to-mariadb-102/)

SourceMod Version: 1.8.0.6024
CS:GO Multi1v1 (1.1.7) by splewis
MYSQL table and columns are utf8_general_ci

**Comment by splewis** [comment] 2018-10-07 21:02
Closing as a duplicate of https://github.com/splewis/csgo-multi-1v1/issues/99.

**Closed by splewis** 2018-10-07 21:02 UTC
Labels: duplicate
